/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clj_blesample_ariset_AirSetActivity */

#ifndef _Included_com_clj_blesample_ariset_AirSetActivity
#define _Included_com_clj_blesample_ariset_AirSetActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clj_blesample_ariset_AirSetActivity
 * Method:    getStr
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clj_blesample_ariset_AirSetActivity_getStr
  (JNIEnv *, jobject, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
