/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_clj_blesample_set_ZeroActivity */

#ifndef _Included_com_clj_blesample_set_ZeroActivity
#define _Included_com_clj_blesample_set_ZeroActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_clj_blesample_set_ZeroActivity
 * Method:    getStr1
 * Signature: ([B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_clj_blesample_set_ZeroActivity_getStr1
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
